# Generated by Django 3.2.5 on 2021-10-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ways_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='false_a',
            field=models.ManyToManyField(related_name='user_false', to='main.Answers'),
        ),
        migrations.AlterField(
            model_name='user',
            name='true_a',
            field=models.ManyToManyField(related_name='user_true', to='main.Answers'),
        ),
    ]
